### ISSUE TITLE
permisson denied exec inside container

### ISSUE THREAD

**Issue by arneboon** [Doodle3D/openwrt-buildroot#8]
```
d191563ad36b: Already exists
Digest: sha256:abb5b033470e9ab247ce4abe2b770036f220b2d40cbd865fcf3d1a8f0551a399
Status: Downloaded newer image for doodle3d/openwrt-buildroot-manual:latest
exec: "/home/openwrt/bin": permission denied
FATA[1572] Error response from daemon: Cannot start container 7b23e03516c0448ae85d5fbd061ba13fe6599d4e1a120fbccffd5ba6c4feed52: [8] System error: exec: "/home/openwrt/bin": permission denied
flash...
studioarneboonmbp:openwrt-buildroot arne$
```

**Comment by arneboon** [comment]
dockerfile sets rights like this:

```
# copy build script into container
COPY Build.sh /home/openwrt/bin/
RUN sudo chmod +x /home/openwrt/bin/Build.sh
```

**Comment by peteruithoven** [comment]
It has to do with our [ENTRYPOINT](http://docs.docker.com/reference/builder/#entrypoint) config. We used the following ENTRYPOINT and CMD: 
```bash
ENTRYPOINT ["/home/openwrt/bin"]
CMD ["Build.sh"]
```
But this mean, when running the container it will try to execute `/home/openwrt/bin`. Also since we also want to support running the container in interactive mode using ENTRYPOINT doesn't seem suitable. So I'll change it to a single CMD. 
```
CMD ["/home/openwrt/bin/Build.sh"]
```

I can't figure out how to change this without rebuilding the image though... You can change config when doing a `docker commit`, but you have to commit from a container. And the command specified to a `docker run` will be used as CMD (no mather how you change the config in the `docker commit`. I can't run it with the command I'd like to have executed on a `docker run`, because that would change the files in the container, changes I don't want to have in the final image. 
Maybe I could have used `docker create`?

**Comment by peteruithoven** [comment]
It has to do with our [ENTRYPOINT](http://docs.docker.com/reference/builder/#entrypoint) config. We used the following ENTRYPOINT and CMD: 
```bash
ENTRYPOINT ["/home/openwrt/bin"]
CMD ["Build.sh"]
```
But this mean, when running the container it will try to execute `/home/openwrt/bin`. Also since we also want to support running the container in interactive mode using ENTRYPOINT doesn't seem suitable. So I'll change it to a single CMD. 
```
CMD ["/home/openwrt/bin/Build.sh"]
```

I can't figure out how to change this without rebuilding the image though... You can change config when doing a `docker commit`, but you have to commit from a container. And the command specified to a `docker run` will be used as CMD (no mather how you change the config in the `docker commit`. I can't run it with the command I'd like to have executed on a `docker run`, because that would change the files in the container, changes I don't want to have in the final image. 
Maybe I could have used `docker create`?

**Comment by peteruithoven** [comment]
We've re-build the image.
